import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import { connectDB } from './config/db.js';
import authRoutes from './routes/authRoutes.js';
import passwordRoutes from './routes/passwordRoutes.js';
import studentRoutes from './routes/studentRoutes.js';
dotenv.config();
const app=express();
app.use(cors({origin:process.env.CLIENT_URL}));
app.use(express.json());
app.get('/',(req,res)=>res.json({message:'Secure Password Manager API'}));
app.use('/api/auth',authRoutes);
app.use('/api/passwords',passwordRoutes);
app.use('/api/students',studentRoutes);
app.use((err,req,res,next)=>res.status(err.status||500).json({message:err.message||'Server error'}));
connectDB().then(()=>app.listen(process.env.PORT||5000,()=>console.log('🚀 Server running'))).catch(console.error);
